👌 Improve error handling when CONDA environ variable isn't set (#434)
This action uses the preinstalled `miniconda` and determines its installation base path reading the `CONDA` environ variable.
Up until `macOS-12` this worked for all runner images, however `macOS-13` and `macOS-14` (current `macos-latest`) do not install `miniconda` and workflows fail with:

```
Error: The "path" argument must be of type string. Received undefined
```
See #432 

With this change, the error will be:
```
Error: Could not determine conda base path, it seams conda is not installed.
```
On any system without the `CONDA` environ variable set.
And for macos runner images > 12:
```
 Error: Could not determine conda base path, it seams conda is not installed.
  MacOS images newer than "macos-12" (i.e. "macOS-latest") are known to be incompatible with this action due to a missing miniconda installation.
  See: https://github.com/s-weigand/setup-conda/issues/432
```